{
  "uid" : "14d34ea71e736b13",
  "name" : "loginWithCorrectCreds",
  "fullName" : "test.authentication.LoginTestEx.loginWithCorrectCreds",
  "historyId" : "972d0c55b5bf6333980548f0fe889f76",
  "time" : {
    "start" : 1639837317897,
    "stop" : 1639837361391,
    "duration" : 43494
  },
  "status" : "broken",
  "statusMessage" : "java.lang.NullPointerException",
  "statusTrace" : "java.lang.NullPointerException\r\n\tat test.authentication.LoginTestEx.loginWithCorrectCreds(LoginTestEx.java:37)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 4,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "beforeSuite",
    "time" : {
      "start" : 1639837317822,
      "stop" : 1639837317829,
      "duration" : 7
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "afterMethod",
    "time" : {
      "start" : 1639837361432,
      "stop" : 1639837361838,
      "duration" : 406
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "81e65196f9248173",
      "name" : "loginWithCorrectCreds",
      "source" : "81e65196f9248173.png",
      "type" : "image/png",
      "size" : 156717
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "afterSuite",
    "time" : {
      "start" : 1639837361849,
      "stop" : 1639837362501,
      "duration" : 652
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "package",
    "value" : "test.authentication.LoginTestEx"
  }, {
    "name" : "testClass",
    "value" : "test.authentication.LoginTestEx"
  }, {
    "name" : "testMethod",
    "value" : "loginWithCorrectCreds"
  }, {
    "name" : "parentSuite",
    "value" : "Default Suite"
  }, {
    "name" : "suite",
    "value" : "appium-maven-project"
  }, {
    "name" : "subSuite",
    "value" : "test.authentication.LoginTestEx"
  }, {
    "name" : "host",
    "value" : "CTC-LAPT-053"
  }, {
    "name" : "thread",
    "value" : "27300@CTC-LAPT-053.main(1)"
  }, {
    "name" : "framework",
    "value" : "testng"
  }, {
    "name" : "language",
    "value" : "java"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "24185208bfd2db71",
      "status" : "broken",
      "statusDetails" : "java.lang.NullPointerException",
      "time" : {
        "start" : 1639757868927,
        "stop" : 1639757913056,
        "duration" : 44129
      }
    }, {
      "uid" : "2dc084081021a557",
      "status" : "broken",
      "statusDetails" : "java.lang.NullPointerException",
      "time" : {
        "start" : 1639756322272,
        "stop" : 1639756342463,
        "duration" : 20191
      }
    }, {
      "uid" : "82588e260c2ca0fa",
      "status" : "broken",
      "statusDetails" : "java.lang.NullPointerException",
      "time" : {
        "start" : 1639754982910,
        "stop" : 1639755004410,
        "duration" : 21500
      }
    }, {
      "uid" : "8c57505c51eb6416",
      "status" : "broken",
      "statusDetails" : "Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20402ms.\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'CTC-LAPT-053', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'\nDriver info: driver.version: AndroidDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20402ms.\n    at getResponseForW3CError (C:\\Users\\anh.vuong.PYCO\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\anh.vuong.PYCO\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'CTC-LAPT-053', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'\nDriver info: driver.version: AndroidDriver",
      "time" : {
        "start" : 1639754578803,
        "stop" : 1639754603607,
        "duration" : 24804
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "14d34ea71e736b13.json",
  "parameterValues" : [ ]
}